name: Build and send to jenkins

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: checkout
       uses: actions/checkout@v4
       
     - name: Set up JDK
       uses: actions/setup-java@v4
       with:
         java-version: "17"
         distribution: 'temurin'

     - name: Build WAR
       run: mvn -B clean package

     - name: Send WAR to Jenkins
       run: curl -u ${{secrets.JENKINS_USER}}:${{secrets.JENKINS_API_TOKEN}} -F "file=@target/myapps.war" -F "json={\"paramater\":[{\"name\":\"WAR_FILE\",\"file\"}]}" ^
            ${{ secrets.JENKINS_URL}}/jpb/deploy-myapp/build
            
       
    
