name: Build and send to Jenkins

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build WAR file
        run: mvn -B clean package

      - name: Send WAR to Jenkins for deployment
        run: |
          curl -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
            -F "file=@target/myapp.war" \
            -F "json={\"parameter\": [{\"name\":\"WAR_FILE\", \"file\":\"file\"}]}" \
             http://10.74.174.9:8080/job/Project2/build
