name: Java CI/CD with Jenkins

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ./artifact

      - name: List downloaded files
        run: ls -lh ./artifact

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://10.74.174.9:8080/job/Insured_Assurance/buildWithParameters?token=auth123" \
            --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
            --data-urlencode "WAR_FILE_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
