name: Java CI/CD with Jenkins

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.war
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: ./artifact

      - name: List downloaded files
        run: ls -lh ./artifact

      - name: Deploy WAR to Jenkins
        run: |
          curl -X POST -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
          -F "file=@./artifact/my-app-1.0-SNAPSHOT.war" \
           "http://https://exp-tr-biographies-economy.trycloudflare.com/job/Insured_Assurance/buildWithParameters?WAR_FILE=my-app-1.0-SNAPSHOT.war"
